### ISSUE TITLE
Error using getCDL

### ISSUE THREAD

**Issue by rtrepos** [jlisic/cdlTools#2]
Hello, and thank you for your work on CDL products.
I was trying this package, and I get this error when using getCDL :

> getCDL("California",c(2013,2015))
failed to load HTTP resource
Erreur : 1: failed to load HTTP resource

Any idea why i get this ?
Best

**Comment by jlisic** [comment]
Not quite sure, let me take a look at it today.

**Comment by jlisic** [comment]
This is confirmed to be an issue on the CRAN side and has been fixed on the GitHub side for a bit.  I'll try to finally get the new version shipped today.

**Comment by rtrepos** [comment]
Thank you it works for me now, I had to put the option ssl.verifypeer to false
