### ISSUE TITLE
varNamesCDL needs to be updated with new classes from 2022

### ISSUE THREAD

**Issue by kevinwolz** [jlisic/cdlTools#23]
It seems that there were some new classes/crops included in the 2022 CDL. These need to be incorporated into `varNamesCDL`. Examples I found are:

70 = Christmas Trees
215 = Avocados
228 = Dbl Crop Triticale/Corn

**Comment by jlisic** [comment]
Thank you so much, I see that Christmas Trees are there, but others are missing.  

I'll go through the 2022 CDLs and see if there is anything else missing.  I'll push a git release tonight (I added terra support and some other things that I need to probably get out the door).

**Comment by kevinwolz** [comment]
@jlisic have you had any success with this?

**Comment by jlisic** [comment]
It should all be there now.
