### ISSUE TITLE
Remove raster dependency

### ISSUE THREAD

**Issue by kevinwolz** [jlisic/cdlTools#24]
This package depends on (imports) the raster package, which is retiring and will no longer be supported (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Even now, continuing to include raster as a dependency means that warnings are generated every time cdlTools is loaded in R.

**Comment by jlisic** [comment]
Thanks Kevin,

Unless I'm reading the article wrong, it just identifies some risk on the retirement of rgdal and rages.  I have mostly moved to terra as an option on all functions in the dev branch except for 'createComparableCDL' which is in progress.  

Reinstalling with current versions of 'sp', 'raster', and 'cdlTools' should remove the warning message.

- With the next release I will provide a one-time loading message that the default reading type will move to terra.  
- Within 6 months I will change the default loading type to terra and move raster to optional.
- Sometime within the next year or two raster will be completely retired.

**Comment by jlisic** [comment]
Version 1.0 that I'm pushing it now supports terra.  Raster will be removed as outlined above.
