### ISSUE TITLE
FIPS Minnesota

### ISSUE THREAD

**Issue by rtrepos** [jlisic/cdlTools#3]
Hi, I get a NA when I call :  fips("Minnesota")
Best

**Comment by jlisic** [comment]
Looks like there is a typo in the data set, let me take care of it on the GitHub side today.

**Comment by jlisic** [comment]
it should be fixed on the GitHub side now, I'll update the package next week.

**Comment by jlisic** [comment]
Looks like I got a bit side tracked, the new version is in CRAN.
