### ISSUE TITLE
Feature: Pull by arbitrary shape files using API.

### ISSUE THREAD

**Issue by jlisic** [jlisic/cdlTools#4]
Implement a wrapper around the WMS calls detailed in the [developer docs](https://nassgeodata.gmu.edu/CropScape/devhelp/help.html).

This was originally implemented but seemed to have some issues in 2016-2017.

**Comment by jsta** [comment]
This detail from the docs seems like it would be a pain:

>  (the .shp, .shx, .dbf, and .prj files must be compressed without directory in a .zip file)_

I would prefer pulling via a bounding box (possibly computed from a shapefile).
