### ISSUE TITLE
Corn class value 251 ?

### ISSUE THREAD

**Issue by rtrepos** [jlisic/cdlTools#7]
Hi,
the corn values are :
1 225 226 237 241 251

Nevertheless when looking at the vat.dbf file and selecting these values I have this :

    VALUE             CLASS_NAME RED    GREEN BLUE OPACITY        
       1                   Corn  1 0.827451    0       1                   
   225   Dbl Crop WinWht/Corn    1 0.827451    0       1  
   226     Dbl Crop Oats/Corn   1 0.827451    0       1     
   237   Dbl Crop Barley/Corn   1 0.827451    0       1   
   241 Dbl Crop Corn/Soybeans   1 0.827451    0       1 
   251                   <NA>   0 0.000000    0       1                

For VALUE = 251, there is no Corn mentioned, can you tell me why 251 is considered as corn ?
Best

**Comment by jlisic** [comment]
Thanks again, let me take a look tonight.  251 is non-irrigated corn, however it may not be present in all of the vat.dbf files.  Is there a particular year/state you are looking at?

**Comment by rtrepos** [comment]
Yes, I tried only California 2010:
CDL_2010_06.tif.vat.dbf
