### ISSUE TITLE
Availability of maps

### ISSUE THREAD

**Issue by rtrepos** [jlisic/cdlTools#8]
Hi,
I understand from you code that the maps are downloaded at this URL :

https://nassgeodata.gmu.edu/cdlservicedata/nass_data_cache/byfips/

- For years 2008 and 2009, which have been recently reprocessed, we can download directly the CDL at the US level. Also some maps (but not all) are available at the State level. For example there is no CDL for Indiana in 2008, (https://nassgeodata.gmu.edu/cdlservicedata/nass_data_cache/byfips/CDL_2008_18.zip) is there a reason for this ?

- Also North Carolina for 2017 contains only 0 values, is this ok ?

Thank you for your help
Best
Ronan

**Comment by jlisic** [comment]
Hi Ronan, I've added a fips code = 99 for all of us downloading.  A lot of this comes down to availability of training data etc... IIRC FSA (maybe it was NASS?) doesn't retain a lot of FSA578 data used to train the classification tree.  So these can't be pre-processed.  

I've send an email to my contacts at NASS about NC 2017.

**Comment by Flash-Of-Thunder** [comment]
Hello Jonathan,

I tried to use the 99 code for the US but was unable to get anything:

`
> US_2008 <- getCDL(x=99, year=2008,location=getwd())
> US_2008
list()
`

DC worked fine
`
> DC_2008 <- getCDL(x=11, year=2008,location=getwd())
> DC_2008
[[1]]
class      : RasterLayer 
dimensions : 746, 623, 464758  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : 1610745, 1629435, 1913745, 1936125  (xmin, xmax, ymin, ymax)
crs        : +proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs 
source     : CDL_2008_11.tif 
names      : CDL_2008_11 
values     : 0, 255  (min, max)
`

Any recommendation on how to get the entire CONUS data?
